# Generated by Django 5.0.6 on 2024-09-10 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='Serial Number')),
            ],
            options={
                'db_table': 'gpstracker',
            },
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_code', models.CharField(max_length=100, unique=True, verbose_name='RFID Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'rfid',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, verbose_name='Zone Name')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('colour', models.CharField(max_length=50, verbose_name='Colour')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Chassis Number')),
                ('insurance', models.BooleanField(default=1, verbose_name='Insurance')),
                ('puc', models.BooleanField(default=1, verbose_name='PUC')),
                ('seating_capacity', models.CharField(max_length=2, verbose_name='Seating Capacity')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Fuel Type')),
                ('air_condition', models.BooleanField(default=1, verbose_name='Air Condition')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPSTracking_App.gpstracker')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='FleetOwnerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleetowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleetowner', to=settings.AUTH_USER_MODEL)),
                ('fleetowner_support_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleetowner_support_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fleetowner_support',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, verbose_name='Driver Name')),
                ('driver_licence_number', models.CharField(max_length=20, verbose_name='Driver Licence Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('valid_till', models.DateField(verbose_name='Valid Till')),
                ('address', models.TextField(verbose_name='Address')),
                ('upload_licence', models.ImageField(upload_to='licence_uploads/', verbose_name='Upload Licence')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPSTracking_App.car')),
                ('rfid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPSTracking_App.rfid', verbose_name='RFID')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Tracker_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30, verbose_name='Zone')),
                ('vendor', models.CharField(max_length=200, verbose_name='Vendor')),
                ('auth_key', models.CharField(max_length=200, verbose_name='Authentication Key')),
                ('latitude', models.FloatField(max_length=10, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=10, verbose_name='Longitude')),
                ('speed', models.FloatField(max_length=10, verbose_name='Speed')),
                ('accuracy', models.FloatField(max_length=10, verbose_name='Accuracy')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('panic', models.BooleanField(default=0, verbose_name='Panic')),
                ('ignition', models.BooleanField(default=0, verbose_name='Ignition')),
                ('air_condition', models.CharField(max_length=10, verbose_name='Air Condition')),
                ('status', models.CharField(default='01', max_length=2)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPSTracking_App.car')),
            ],
            options={
                'db_table': 'tracker_data',
            },
        ),
    ]
