# Generated by Django 5.0.1 on 2024-01-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('colour', models.CharField(max_length=50, verbose_name='Colour')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Chassis Number')),
                ('insurance', models.BooleanField(default=1, verbose_name='Insurance')),
                ('puc', models.BooleanField(default=1, verbose_name='PUC')),
                ('seating_capacity', models.CharField(max_length=2, verbose_name='Seating Capacity')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Fuel Type')),
                ('air_condition', models.BooleanField(default=1, verbose_name='Air Condition')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Password')),
                ('confirm_password', models.CharField(blank=True, max_length=200, verbose_name='Confirm Password')),
                ('contact_number', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
                ('aadhar_number', models.CharField(max_length=12, unique=True, verbose_name='Aadhar Number')),
                ('pan_number', models.CharField(max_length=10, unique=True, verbose_name='PAN Number')),
                ('resident_proof', models.ImageField(upload_to='fleetowner_uploads/', verbose_name='Resident Proof')),
            ],
            options={
                'db_table': 'fleetowner',
            },
        ),
        migrations.CreateModel(
            name='GPSTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='Serial Number')),
            ],
            options={
                'db_table': 'gpstracker',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, verbose_name='Driver Name')),
                ('driver_licence_number', models.CharField(max_length=20, verbose_name='Driver Licence Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('valid_till', models.DateField(verbose_name='Valid Till')),
                ('address', models.TextField(verbose_name='Address')),
                ('upload_licence', models.ImageField(upload_to='licence_uploads/', verbose_name='Upload Licence')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPSTracking_App.car')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPSTracking_App.fleetowner'),
        ),
        migrations.AddField(
            model_name='car',
            name='tracker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPSTracking_App.gpstracker'),
        ),
        migrations.CreateModel(
            name='Tracker_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30, verbose_name='Zone')),
                ('vendor', models.CharField(max_length=200, verbose_name='Vendor')),
                ('auth_key', models.CharField(max_length=200, verbose_name='Authentication Key')),
                ('latitude', models.FloatField(max_length=10, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=10, verbose_name='Longitude')),
                ('speed', models.CharField(max_length=10, verbose_name='Speed')),
                ('accuracy', models.CharField(max_length=10, verbose_name='Accuracy')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('panic', models.BooleanField(default=0, verbose_name='Panic')),
                ('ignition', models.BooleanField(default=1, verbose_name='Ignition')),
                ('air_condition', models.CharField(max_length=10, verbose_name='Air Condition')),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GPSTracking_App.car')),
            ],
            options={
                'db_table': 'tracker_data',
            },
        ),
    ]
