# Generated by Django 5.0.1 on 2024-01-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPSTracking_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_code', models.CharField(max_length=100, unique=True, verbose_name='RFID Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'rfid',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='rfid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPSTracking_App.rfid', verbose_name='RFID'),
        ),
    ]
